<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Orders\Features\CreateOrder\" />
    <Folder Include="Orders\Features\DeleteOrder\" />
    <Folder Include="Orders\Features\GetOrderById\" />
    <Folder Include="Orders\Features\GetOrders\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
