services:
  eshopdb:
    image: postgres

  seq:
    image: datalust/seq:latest

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: Bootstrapper/Api
      dockerfile: Dockerfile


volumes:
  postgres_eshopdb:


